name: Latest blog post workflow

on:
  schedule:
    - cron: "0 */12 * * *"    # checks twice a day for new posts
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write             # required to write the generated content to the readme

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull in latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dhanushkumarr.blogspot.com/feeds/posts/default?alt=rss"
          max_post_count: 3
