name: Latest blog post workflow

on:
  schedule:
    - cron: "0 */12 * * *"    # checks twice a day for new posts
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Pull in latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v2
        with:
          feed_list: "https://dhanushkumarr.blogspot.com/feeds/posts/default?alt=rss"
          max_post_count: 3
